### ISSUE TITLE
Can not select doors or windows

### ISSUE THREAD

**Issue by axute** [AndySymons/Heating-X2-code-generator#4]
Hello, I try your blueprint, but can not select my door and window sensors.
there are more classes for this domain on  [#91](https://github.com/AndySymons/HEATHER-Home-Heating-Control-for-Home-Assistant-/blob/242b6b0e10ae336350f46b431fb2b7abc777b3df/Blueprints/heating_x2.yaml#L91), like window, door.

Can you extend it with the possible classes?

![image](https://github.com/user-attachments/assets/4b73a599-a35e-41d1-943c-e137b171b19a)

Thank you very much, I'll try to grind it in somehow ;-)

**Comment by AndySymons** [comment]
I set it up for the input domain to be `binary_sensor` as that is usual for door and window closure sensors. However you can easily change this by changing line 90 of the blueprint to list other domains or remove it to accept all domains.
See the Home Assistant [Blueprint entity selector documentation](https://www.home-assistant.io/docs/blueprint/selectors/#entity-selector)
 
Alternatively you could write binary_sensor template sensors for your devices that are not binary sensors, and use them as inputs to the blueprint. 
See the Home Assistant [Template documentation](https://www.home-assistant.io/integrations/template/#state-based-template-binary-sensors-buttons-images-numbers-selects-and-sensors)

**Comment by axute** [comment]
I think the problem is the device class "opening". If I define my windows as openings, I have different icons. If it could be a window or a door, couldn't I also add window and door to the device class (list) like in the Home Assistant documentation?

**Comment by AndySymons** [comment]
Yes of course you can modify the domain and device class in the template selectors to [any valid value](https://www.home-assistant.io/integrations/binary_sensor/#device-class), including 'window' and 'door' 
All the selector values do is limit what is on the drop-down list when you invoke the template. 

In my case my window and door sensors all configured by default as device class 'opening' and I left them at that, then changed the _icon_ for display on the dashboard -- but your approach looks more thorough!
